"""image

Revision ID: 1eb96fc3fa12
Revises: 
Create Date: 2026-05-07 23:16:01.284426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb96fc3fa12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exercises', 'profiles', ['profile_id'], ['id'])
    op.add_column('profiles', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('workouts', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workouts_profile_id'), 'workouts', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'workouts', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_index(op.f('ix_workouts_profile_id'), table_name='workouts')
    op.drop_column('workouts', 'profile_id')
    op.drop_column('profiles', 'profile_image')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    # ### end Alembic commands ###
